# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdminAddProducts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdminAddProducts
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftSpinner'
  pod 'KeychainSwift', '~> 19.0'

end
